### PR TITLE
Staging for version increment automation

### PR DESCRIPTION
**Pull request by prudhvigodithi**
Signed-off-by: pgodithi <pgodithi@amazon.com>

*Issue #, if available:*
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/index-management/issues/404

*Description of changes:*
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/index-management/pull/1

*CheckList:*
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/index-management/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Referred old version increment PR:
https://github.com/opensearch-project/index-management/pull/377

**Comment by prudhvigodithi** [comment]
Renaming to task updateVersion following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

**Comment by bbarani** [comment]
@downsrob  @praveensameneni can you please review this PR soon?

**Comment by downsrob** [comment]
@prudhvigodithi 
Tried it locally and everything looks good. That said, I would have liked to be able to update buildVersionQualifier as well through another system property with this task so we can automate that version change when the time comes as well.

**Review by downsrob — APPROVED** [review]

**Review by praveensameneni — APPROVED** [review]

**Pull request merged**
