### PR TITLE
Updates index management version to 1.2

### PR DESCRIPTION
**Pull request by downsrob**
Signed-off-by: Clay Downs downsrob@amazon.com
*Issue #, if available:*
https://github.com/opensearch-project/opensearch-build/issues/663
*Description of changes:*
Updates index management version to 1.2. Changes the gradle build file, as well as the github test and build workflows.
*CheckList:*
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/index-management/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Since this is to include IM into the 1.2.0 bundle, can we please address https://github.com/opensearch-project/index-management/issues/155 part of this as well? See https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#consume-maven-artifacts-in-order that was just added to explain the order of maven dependencies required.

**Comment by dbbaughe** [comment]
@dblock Yes, we plan to merge in the common utils and job scheduler 1.2 version changes first. Let those get published to the snapshot repository, and then do the IM changes. We can add back the mavenLocal repo at that time too.

**Comment by dblock** [comment]
Ok cool, I want to gate adding into the 1.2 manifest any plugins that haven't moved to using maven. This way we don't have to chase them separately.

**Comment by dbbaughe** [comment]
Sure, Clay is making the changes in common utils and job scheduler to depend on the staging repo

**Comment by dbbaughe** [comment]
@downsrob Ah you're in a bit of a predicament now... looks like it's trying to find the alerting notification subproject 1.2 on maven.. so you *could* go and now bump alerting main to 1.2 and whatever else is needed to get that notification subproject published to the staging repo.. but at the same time.. I *think* we're trying to remove it in 1.2, but we haven't merged back in the support for notification plugin yet in Index Management as we are waiting to confirm it'll go out in 1.2.

**Review by dbbaughe — APPROVED** [review]

**Pull request merged**
