### PR TITLE
Incremented version to 1.2.3.

### PR DESCRIPTION
**Pull request by dblock**
Coming from https://github.com/opensearch-project/opensearch-build/issues/1365.

### CODE REVIEW

**Review by downsrob — APPROVED** [review]

**Review by peternied — APPROVED** [review]
Is there an issue for this binary?

**Comment by downsrob** [comment]
@peternied Yes, here is the issue for it https://github.com/opensearch-project/index-management/issues/123

**Comment by dblock** [comment]
> @peternied Yes, here is the issue for it #123

Ironically issue 123 (1.2.3)

**Comment by usabada** [comment]
I don't see this release version updated in https://github.com/opensearch-project/index-management/releases

**Pull request merged**
