### PR TITLE
Fix for test failure related to SnapshotInfo object creation

### LINKED ISSUE #1236: [BUG] Gradle tests failing due to compile-time errors introduced in TestUtils.kt for SnapshotInfo class
**What is the bug?**
ISM gradle tests are failing with the below mentioned error since yesterday.
```
./gradlew integTest  --tests 'org.opensearch.indexmanagement.indexstatemanagement.action.CloseActionIT.test basic'
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.5
  OS Info               : Linux 5.15.153.1-microsoft-standard-WSL2 (amd64)
  JDK Version           : 11 (Ubuntu JDK)
  JAVA_HOME             : /usr/lib/jvm/java-11-openjdk-amd64
  Random Testing Seed   : 3F3E8394EF4FFEC6
  In FIPS 140 mode      : false
=======================================

> Task :compileTestKotlin
e: file:///home/opensearch-project-index-management/src/test/kotlin/org/opensearch/indexmanagement/snapshotmanagement/TestUtils.kt:222:9 None of the following functions can be called with the arguments supplied:
public constructor SnapshotInfo(p0: SnapshotsInProgress.Entry!) defined in org.opensearch.snapshots.SnapshotInfo
public constructor SnapshotInfo(p0: StreamInput!) defined in org.opensearch.snapshots.SnapshotInfo
public constructor SnapshotInfo(p0: SnapshotId!, p1: (Mutable)List<String!>!, p2: (Mutable)List<String!>!, p3: Long, p4: String!, p5: Long, p6: Int, p7: (Mutable)List<SnapshotShardFailure!>!, p8: Boolean!, p9: (Mutable)Map<String!, Any!>!, p10: Boolean!, p11: Long) defined in org.opensearch.snapshots.SnapshotInfo
public constructor SnapshotInfo(p0: SnapshotId!, p1: (Mutable)List<String!>!, p2: (Mutable)List<String!>!, p3: SnapshotState!) defined in org.opensearch.snapshots.SnapshotInfo
public/*package*/ constructor SnapshotInfo(p0: SnapshotId!, p1: (Mutable)List<String!>!, p2: (Mutable)List<String!>!, p3: SnapshotState!, p4: String!, p5: Version!, p6: Long, p7: Long, p8: Int, p9: Int, p10: (Mutable)List<SnapshotShardFailure!>!, p11: Boolean!, p12: (Mutable)Map<String!, Any!>!, p13: Boolean!, p14: Long) defined in org.opensearch.snapshots.SnapshotInfo
public constructor SnapshotInfo(p0: SnapshotId!, p1: (Mutable)List<String!>!, p2: (Mutable)List<String!>!, p3: SnapshotState!, p4: Version!) defined in org.opensearch.snapshots.SnapshotInfo

```

**Details:**
Branch: main
Platform: linux

**How can one reproduce the bug?**
1. Clone the project git@github.com:opensearch-project/index-management.git
2. Run some integration/ut tests. For ex. 
```
     ./gradlew integTest  --tests 'org.opensearch.indexmanagement.indexstatemanagement.action.CloseActionIT.test basic'
    or
     ./gradlew test --tests 'org.opensearch.indexmanagement.snapshotmanagement.engine.states.creation.CreatingStateTests.*'
```

**What is the expected behavior?**
Tests must pass.
 
**Do you have any additional context?**
This issue is seen since this PR [#15124](https://github.com/opensearch-project/OpenSearch/pull/15124/files#diff-e6fa71852f7522df91474eb81a58eed36f7f410fbe8e33816c8cc1978d9c0928) is merged in Opensearch repo yesterday. The class SnapshotInfo has an additional new parameter **pinnedTimestamp** which needs to be set in the constructor, when creating an object.

### PR DESCRIPTION
**Pull request by aggarwalShivani**
### Description
To resolve the compile-time error caused due to change in [SnapshotInfo](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java) class, I've updated the TestUtils.kt to create the object of SnapshotInfo with additional pinnedTimestamp (0) parameter.

Kindly let me know if this solution is fine :)

### Related Issues
Resolves #1236 

### Check List
- ~[ ] New functionality includes testing.~
- ~[ ] New functionality has been documented.~
- ~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
- [x] Commits are signed per the DCO using `--signoff`.
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/index-management/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by aggarwalShivani** [comment]
Hi Reviewers, 
Requesting feedback for this minor fix :)

**Comment by dblock** [comment]
cc: @vikasvb90 

Tests are failing in this PR though, so the fix is not enough to merge.

**Comment by bowenlan-amzn** [comment]
@aggarwalShivani please merge with main once, see if that will help test run

**Comment by vikasvb90** [comment]
Thanks @dblock for notifying! 
@aggarwalShivani There is already a method in SnapshotInfo  ( [code pointer](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java#L357-L369)) which doesn't need `pinnedTimestamp`. 
Can you please add details on which workflow/test failure is it fixing?

**Comment by vikasvb90** [comment]
The failing tests in your PR are because of recent deprecation in upload-artifacts. Can you check if you are still getting a `compile-time` error? It could have been already fixed by a PR.

**Comment by vikasvb90** [comment]
Closing this PR since the change isn't fixing anything. Please reopen if you see any other issue. Thanks!

**Comment by aggarwalShivani** [comment]
Hi, 
Yes, looks like, a few other changes were made to the SnapshotInfo class after this PR was raised :)  
This change is no longer needed, and the issue seems resolved.
Thanks!

**Pull request closed without merging**
