### PR TITLE
[Release 1.3.5] Version increment and add `build.sh`

### PR DESCRIPTION
**Pull request by prudhvigodithi**
*Issue #, if available:*

*Description of changes:*
Incremented version to 1.3.5.
Part of: https://github.com/opensearch-project/opensearch-build/issues/2348

*CheckList:*
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/index-management/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
CI needs to pass.

**Comment by prudhvigodithi** [comment]
Hey @downsrob @praveensameneni can you please review this PR?

**Comment by dblock** [comment]
@prudhvigodithi There are more files to increment the version in, see https://github.com/opensearch-project/index-management/pull/407 for an example.

**Comment by prudhvigodithi** [comment]
Right but that was before this issue was fixed https://github.com/opensearch-project/index-management/issues/402, now AFAIK we dont need to update the workflows.
@downsrob

**Comment by dblock** [comment]
In 1.x notification comes from alerting -> https://github.com/opensearch-project/opensearch-build/pull/2474

**Review by bowenlan-amzn — APPROVED** [review]

**Pull request merged**
